version: "2.0"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: sqlinjection-docker
    ports:
      - "8081:80"
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: zwitscher
      DB_USERNAME: zwitscher
      DB_PASSWORD: zwitscher

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      #      MYSQL_DATABASE: sectrain
      # MYSQL_USER: sectrain
      #      MYSQL_PASSWORD: 2P6KMhFDx3uW5Bdr
      MYSQL_ROOT_PASSWORD: 2P6KMhFDx3uW5Bdr
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
