version: "2.0"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: sqlinjection-docker
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: zwitscher
      DB_USERNAME: zwitscher
      DB_PASSWORD: zwitscher
  mysql:
    image: mysql:5.7
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
